dist: bionic
addons:
    apt:
        packages:
            - libpoppler-cpp-dev

language: python
python:
    - "2.7"
    - "3.6"

install:
    - pip install pybind11==2.4.3 Pillow==5.4.1

script:
    - python setup.py test
