dist: focal
addons:
    apt:
        packages:
            - libpoppler-cpp-dev

language: python
python:
    - "3.8"

install:
    - pip install pybind11==2.6.1 Pillow==8.0.1

script:
    - python setup.py test
